travis:
  secure:
    BINSTAR_TOKEN: wEfCgN7i6VXyvNtVdW520D/9sC5FFWqX8mjon4t9deWwwVmxEGx6+zfN4HY1R57kMEQY7JHX6W1z5OcbA1JYpCRbERRuY5WITGxxXdlJPpg65HmV7ls+JBwAYzPBprWfAzMJiSVHaC1V/1HOPyKSbm7bfrNU4/uaDsIAzWCj4Dknw/4SlHF0r05CZjy5rH5lMzwFkMiKGZmj8XWzKDPy/W9ibYfkDdX8X3n3G0aE3NIirn+6GJK6TDnTW1MUg5tANIbdn7T+8G+TVLLodyIJVmfSoUA6u4fpdAH2+1a+mXloN405lXbswgOVvs+OLsxq3zMDVDfXY8MhwzJB79D01oLz2uQMKSRPvsBnaOB0vc06btM2yrURO9kmlKc0B6uDz6TPMsQ8QAnasiZ6F+V0Mw26k6DgUkA8O4MOg9jot4QrgMnIjXfLZFKaOXlZ++wDM6loAhq1WCW5flLXoySuuhea8LWf0fR3LtARteSIKPFF4ijCmtSWrQ0DOoc2bUCqk0DZgAa3elT0F9Yg5k07bDqnwR5SqKBg3yVjgx3KPkExqt3CgBRAg9ecmnMGgU4MDDwgtXp9bCUnIQzRpg3n8H/eH1ST/PIupfC6QYr2+0rHNk2mSoqO1le5bfG2sEd0pqJ6Hp/xsR/IXtq1ZJ4N/A6MTMZQrzk7vGDA1zd0EeI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
