travis:
  secure:
    BINSTAR_TOKEN: O4RLk+wBajg3t6xhNV3XwjBM/gwwh5UxGOd5bhNV4XgoEkEG1819iURNbXaiEn8TTJ4C4TVXcA4Y58fj5CioipQ7uQTuUnctntmNVsK4gMxWQY/MOUrNh7qFb1LUzoPUi/C32SLLetsWZtNpxkhp+J3t9e4ChZ+873LiV8FmNU51aO3HIhc+doKRbIl70bw7HB0IaxQVRtRST4eEVJzhRcMcVRw5hlpsgy3Omv/xvGYelCRIvkB3wqBQRr8MCLe77RI1yTnDz0Rfg9nejBXZQu/lp1jitFqx2innYF0eaio+zzKjkpAlKXfntDWOPj87OxSk1tR19f9I+oGYGw4HIFyKbTalX0ISomarl6QjI6Q+31HX1Q0JZRW9ttHIRJH/EkvuXX7BbYi9rpnNq2ZkfscZLT4OU+pG8QQYJBtcQV+iW+47QY4nfSyfZf/FB/s5ObolqYtWxyYYHWHbvyfARcNErnWT1JNBo9DP8YPU5Fqsz8TBjjPpJOmBMk6XBzrjj2vDqiTirpJpL0RxHtKYDTdDbnYC7ZwfBQlxLfcDBJfBO+nWlC9c2XgkojK02o1Q36nAyeah3A/a0c0PUuBo/ryXt0hy8Q9/Y7ebQszud58pMUA9t2FcFm4rgKd0R2oq0ZHDYr15QIK0CNyYuv2C2DgLawoupx/TNpvibPYmVUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
